fix: Docker build error and add dockerignore file to repo
9 1.598 ERROR: unable to select packages:
------
 > [ 5/11] RUN apk add tesseract-ocr tesseract-ocr-data-eng ocrmypdf --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community:
0.246 fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
0.707 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
1.008 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
1.598 ERROR: unable to select packages:
1.603   so:libicui18n.so.76 (no such package):
1.603     required by: tesseract-ocr-5.5.0-r2[so:libicui18n.so.76]
1.603   so:libicuuc.so.76 (no such package):
1.603     required by: tesseract-ocr-5.5.0-r2[so:libicuuc.so.76]
------

 4 warnings found (use docker --debug to expand):
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "RAILS_MASTER_KEY") (line 37)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "RAILS_MASTER_KEY") (line 38)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "RAILS_SECRET_KEY_BASE") (line 39)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "SECRET_KEY_BASE") (line 40)
Dockerfile:15
--------------------
  13 |     RUN apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES
  14 |
  15 | >>> RUN apk add tesseract-ocr tesseract-ocr-data-eng ocrmypdf --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community
  16 |
  17 |     COPY Gemfile Gemfile.lock ./
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add tesseract-ocr tesseract-ocr-data-eng ocrmypdf --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community" did not complete successfully: exit code: 6